import { PreflightSummary, ImportSummary } from '../CatalogResults.jsx';
import { estimateImportDurationMs, formatDuration } from '../importTiming.js';

export default function ImportFlowPage({ stage, scope, result, preflightError, importError, preflightLoading, importLoading, catalog, selectedCount, dryRunMode, testModeEnabled, baseApiRequestsPerMinute, importReadStrategy, onBack, onContinue, onImport, onCatalog }) {
  const scopeLabel = scope === 'full' ? 'catalogo completo' : 'prodotti selezionati';
  const ready = result?.products?.readyForBase;
  const estimate = ready != null ? estimateImportDurationMs(ready, baseApiRequestsPerMinute, { dryRun: dryRunMode, ...importReadStrategy }) : null;
  return <div className="page-stack">
    <div className="page-heading"><div><div className="flow-breadcrumb">Catalogo <span>›</span> <strong className={stage === 'preflight' ? 'active' : ''}>Controlli preliminari</strong> <span>›</span> <strong className={stage === 'confirmation' ? 'active' : ''}>Conferma import</strong> <span>›</span> <strong className={stage === 'result' ? 'active' : ''}>Risultato</strong></div><h1>{stage === 'preflight' ? 'Controlli preliminari' : stage === 'confirmation' ? 'Conferma importazione' : 'Risultato importazione'}</h1><p>Operazione: {scopeLabel}.</p></div></div>
    {stage === 'preflight' && <>{preflightLoading && <div className="card working" role="status"><span className="spinner" /> Controlli preliminari in corso…</div>}{preflightError && <div className="alert alert-danger" role="alert">Controlli preliminari non riusciti: {preflightError}</div>}{result && <PreflightSummary result={result} title="Controlli preliminari completati" />}<div className="flow-actions"><button className="btn btn-secondary" type="button" onClick={onBack}>Torna alle operazioni</button>{result && ready > 0 ? <button className="btn btn-primary" type="button" onClick={onContinue}>Continua alla conferma</button> : result && <p>Nessun prodotto è pronto per l’importazione.</p>}</div></>}
    {stage === 'confirmation' && result && <><section className="card confirmation-card"><div className="card-heading"><div><h2>Rivedi l’operazione</h2><p>I controlli sono terminati. La conferma finale resta obbligatoria prima dell’avvio.</p></div></div><dl className="detail-list"><div><dt>Fornitore</dt><dd>{result.supplier?.sourceTitle || catalog?.channelTitle || 'Non disponibile'}</dd></div><div><dt>Importazione</dt><dd>{scope === 'full' ? 'Catalogo completo' : 'Prodotti selezionati'}</dd></div><div><dt>Prodotti {scope === 'full' ? 'nel catalogo' : 'selezionati'}</dt><dd>{scope === 'full' ? catalog?.totalProducts : selectedCount}</dd></div><div><dt>Pronti per Base.com</dt><dd>{ready}</dd></div><div><dt>Modalità</dt><dd>{dryRunMode === true ? 'Simulazione' : dryRunMode === false ? 'Reale' : 'Da verificare'}</dd></div>{result.products?.unmappedValidCategory > 0 && <div><dt>Esclusi per categoria non mappata</dt><dd>{result.products.unmappedValidCategory}</dd></div>}</dl></section>
      {estimate != null && <div className="alert alert-info">Stima indicativa dal ritmo delle richieste Base.com: circa {formatDuration(estimate)} {dryRunMode ? 'senza scritture' : 'se tutti i prodotti richiedono una scrittura'}. La durata reale può variare.</div>}
      {testModeEnabled && <div className="alert alert-warning">Modalità test attiva: l’import dei prodotti è limitato dal backend.</div>}
      {dryRunMode === true && <div className="alert alert-warning"><strong>Simulazione: nessuna modifica verrà scritta su Base.com.</strong></div>}
      {dryRunMode === false && <div className="alert alert-danger"><strong>ATTENZIONE: modalità reale. L’importazione può modificare Base.com.</strong></div>}
      <div className="flow-actions"><button className="btn btn-secondary" type="button" onClick={onBack}>Torna ai controlli</button><button className="btn btn-primary" type="button" disabled={importLoading || typeof dryRunMode !== 'boolean' || !(ready > 0)} onClick={onImport}>{importLoading ? 'Importazione in corso…' : 'Conferma e avvia importazione'}</button></div></>}
    {stage === 'result' && <>{importLoading && <div className="card working" role="status"><span className="spinner" /> Importazione in corso…</div>}{importError && <div className="alert alert-danger" role="alert">{importError}</div>}{result && <ImportSummary result={result} dryRunMode={dryRunMode} />}<div className="flow-actions"><button className="btn btn-secondary" type="button" onClick={onCatalog}>Torna al catalogo</button></div></>}
  </div>;
}
