export default function OperationsPage({ catalog, selectedCount, catalogBusy, dryRunMode, fullPreflightLoading, preflightLoading, manufacturerSyncLoading, manufacturerSyncError, manufacturerSyncResult, onPreflightFull, onPreflightSelected, onSync, onCatalog }) {
  return <div className="page-stack"><div className="page-heading"><div><h1>Operazioni</h1><p>Controlli e sincronizzazioni disponibili per il catalogo caricato.</p></div></div>
    {!catalog && <div className="alert alert-info">Carica un catalogo Vudoo per attivare le operazioni. <button className="text-link" onClick={onCatalog} type="button">Apri Catalogo Vudoo</button></div>}
    <div className="operations-grid">
      <section className="card operation-card"><span className="operation-icon">01</span><h2>Catalogo completo</h2><p>Analizza tutto il catalogo e prepara l’importazione completa.</p><div className="operation-meta">{catalog ? `${catalog.totalProducts} prodotti ricevuti` : 'Catalogo non caricato'}</div><button className="btn btn-primary" type="button" disabled={!catalog || catalogBusy} onClick={onPreflightFull}>{fullPreflightLoading ? 'Controlli in corso…' : 'Esegui controlli preliminari'}</button></section>
      <section className="card operation-card"><span className="operation-icon">02</span><h2>Prodotti selezionati</h2><p>Analizza soltanto gli ID scelti nella pagina Catalogo.</p><div className="operation-meta">{catalog ? `${selectedCount} prodotti selezionati` : 'Catalogo non caricato'}</div><button className="btn btn-secondary" type="button" disabled={!catalog || !selectedCount || catalogBusy} onClick={onPreflightSelected}>{preflightLoading ? 'Controlli in corso…' : 'Verifica selezionati'}</button></section>
      <section className="card operation-card"><span className="operation-icon">03</span><h2>Produttori</h2><p>Sincronizza i produttori presenti nel catalogo caricato.</p><div className="operation-meta">{dryRunMode === true ? 'Simulazione attiva' : dryRunMode === false ? 'Modalità reale attiva' : 'Modalità da verificare'}</div><button className="btn btn-secondary" type="button" disabled={!catalog || catalogBusy || typeof dryRunMode !== 'boolean'} onClick={onSync}>{manufacturerSyncLoading ? 'Sincronizzazione in corso…' : 'Sincronizza produttori'}</button>{manufacturerSyncError && <div className="alert alert-danger" role="alert">{manufacturerSyncError}</div>}{manufacturerSyncResult && <div className="alert alert-success" role="status">{dryRunMode ? 'Sincronizzazione simulata completata.' : 'Sincronizzazione completata.'}</div>}</section>
    </div>
  </div>;
}
